[Main]
executorlib = True
method = NEB
dir_path = /work/08405/ilgar/vista/tsearch/examples/catsunami/datasets/all_dft_neb_trajs  # reads all *.traj files in this directory
Optimizer = MDMin
jobs_per_gpu = 4
Calculator = FAIRChemCalculator
fmax = 0.05
steps = 2000

[FAIRChemCalculator]
device = cuda
name_or_path = uma-s-1p1
task_name = oc20

[MDMin]
dt = 0.05
maxstep = 0.1


######################## NEB related ########################
[ourNEB]
relax_endpoints = True
endpoint_relax_fmax = 0.05
endpoint_relax_steps = 300
interpolate_method = False
num_frames = 10
batch_size = 8

[DyNEB]
k = 5
climb = True
method = improvedtangent
allow_shared_calculator = True
dynamic_relaxation = False
