[Main]
executorlib = True
method = NEB
dir_path = /work/08405/ilgar/ls6/tsearch/examples/catsunami/datasets/all_dft_neb_trajs/transfers  # reads all *.traj files in this directory
Optimizer = MDMin
jobs_per_gpu = 1
Calculator = FAIRChemCalculator  # In the future this could also be Vasp and VaspInteractive
fmax = 0.05
steps = 3000

[Vasp]
setups = minimal
# ibrion = 2
# nsw = 2000
isif = 0
ispin = 1
isym = 0
lreal = Auto
ediff = 0.00001
ediffg = -0.03
symprec = 1e-10
encut = 350.0
# laechg = False
# lwave = False
# ncore = 4
gga = RP
pp = PBE
xc = PBE

[MDMin]
dt = 0.05
maxstep = 0.1


######################## NEB related ########################
[ourNEB]
relax_endpoints = True
endpoint_relax_fmax = 0.05
endpoint_relax_steps = 300
interpolate_method = False
num_frames = 10
batch_size = 8
vasp_command_endpoints = "export I_MPI_PMI_LIBRARY=/usr/lib64/libpmi2.so; srun --mpi=pmi2 --exclusive -n 64 /home1/07700/sjung3/vasp/vasp.6.4.0.1/bin/vasp_std"
vasp_ncore_endpoints = 8
vasp_command_intermediates = "export I_MPI_PMI_LIBRARY=/usr/lib64/libpmi2.so; srun --mpi=pmi2 --exclusive -n 16 /home1/07700/sjung3/vasp/vasp.6.4.0.1/bin/vasp_std"
vasp_ncore_intermediates = 4

[DyNEB]
k = 5
climb = True
method = improvedtangent
allow_shared_calculator = True
dynamic_relaxation = False
