[Main]
executorlib = True
method = NEB
dir_path = /scratch/08405/ilgar/OC20NEB/done_by_saddlemill/NEB_debug_zips  # reads all *.traj files in this directory
Optimizer = MDMin
device = 'cpu'
Calculator = VaspInteractive
fmax = 0.05
steps = 300

[Vasp]
setups = minimal
# ibrion = 2
# nsw = 2000
isif = 0
ispin = 1
isym = 0
lreal = Auto
ediff = 0.00001
# ediffg = -0.03
symprec = 1e-10
encut = 350.0
# laechg = False
# lwave = False
# ncore = 4
gga = RP
pp = PBE
xc = PBE

[MDMin]
dt = 0.05
maxstep = 0.1

[LBFGS]
memory = 20
damping = 0.99
alpha = 200
maxstep = 0.1
use_line_search = False


######################## NEB related ########################
[ourNEB]
relax_endpoints = True
endpoint_relax_Optimizer = LBFGS
endpoint_relax_fmax = 0.05
endpoint_relax_steps = 200
interpolate_method = False
images_location_in_input_traj = -1
num_frames = 10
# batch_size = 8
vasp_command_endpoints = "unset PMI2_FD PMI_FD PMI2_RANK PMI_RANK PMI2_SIZE PMI_SIZE PMI2_SPROUTE; I_MPI_HYDRA_BOOTSTRAP=fork /opt/intel/compilers_and_libraries_2020.4.304/linux/mpi/intel64/bin/mpirun -n 64 /home1/07700/sjung3/vasp/vasp.6.4.0.1/bin/vasp_std"
vasp_ncore_endpoints = 8
vasp_command_intermediates = "unset PMI2_FD PMI_FD PMI2_RANK PMI_RANK PMI2_SIZE PMI_SIZE PMI2_SPROUTE; I_MPI_HYDRA_BOOTSTRAP=fork /opt/intel/compilers_and_libraries_2020.4.304/linux/mpi/intel64/bin/mpirun -n 16 /home1/07700/sjung3/vasp/vasp.6.4.0.1/bin/vasp_std"
vasp_ncore_intermediates = 4

[BaseNEB]
k = 5
climb = True
method = improvedtangent
allow_shared_calculator = True
