[Main]
executorlib = True
method = Dimer
dir_path = /work/07700/sjung3/vista/genTS/datasets/oc20/converged_1part/partitioned_in_3/dir1  # reads all *.traj files in this directory
jobs_per_gpu = 6
Calculator = FAIRChemCalculator  # In the future this could also be Vasp and VaspInteractive
fmax = 0.05
steps = 500

[FAIRChemCalculator]
device = cuda
model_name_or_path = uma-s-1p1
task_name = oc20


######################## Dimer related ########################
[ourDimer]
dataset_type = oc  # could also be "bulk"
num_attempts = 3
delocalization_threshold = 0.8
extension_check_fmax = 0.4
extension_check_curvature = -0.2

[DimerControl]
max_num_rot = 10
initial_eigenmode_method = displacement
maximum_translation = 0.1
dimer_separation = 0.01
extrapolate_forces = True
displacement_method = gauss
gauss_std = 0.1
displacement_radius = 3.3
