"""Validated component assembly for SaddleMill minimum-mode searches.

This module is the structural boundary that was previously embedded in
``dimeropt._setup_dimer``.  It does not rewrite the existing Dimer, Kappa,
Lanczos, Davidson, rotational L-BFGS, legacy translation L-BFGS, or FIRE-LBFGS
numerical implementations.  It selects those existing implementations and adds
an opt-in projection-independent force-history layer.
"""

from __future__ import annotations

from typing import Mapping
import json
import hashlib

import numpy as np

from saddlemill.dimertools.force_history import normalise_tokens


DEFAULT_HISTORY_OPTIONS: dict[str, object] = {
    # Storage/instrumentation.  False means legacy objects are constructed
    # exactly as before.  canonical_lbfgs turns this on automatically.
    "enabled": False,
    "rotation_reuse": False,
    # Backward-compatible default: rotation_reuse=True alone retains the
    # previously installed derived-pair cache.  New canonical runs must select
    # rotation_history_source=force_bank explicitly.
    "rotation_history_source": "legacy_derived",
    "rotation_max_pairs": 0,
    "rotation_pair_sources": "consecutive_physical",
    "rotation_accepted_force_source": "physical_only",
    "rotation_trial_pairs_future_only": False,
    "rotation_cosine_threshold": "off",
    "memory_states": 20,
    "max_probes_per_state": 0,
    "center_tolerance": 1.0e-12,
    "sample_tolerance": 1.0e-12,
    "record_sources": "center rotation lanczos davidson reference_hessian translation_trial",
    # Consumer policy.  center_center is the clean comparison with historical
    # translation L-BFGS; adding center_rotation isolates force reuse.
    "pair_sources": "center_center",
    "pair_order": "acquisition",
    "projection_policy": "current_snapshot",
    "kappa_projection_policy": "fixed_current_center_coefficients",
    # Default to rejecting poor curvature pairs. Powell is opt-in.
    "pair_safeguard": "skip",
    "curvature_floor": 1.0e-3,
    "curvature_epsilon": 1.0e-12,
    "powell_eta": 0.2,
    "cosine_threshold": "off",
    "cautious_epsilon": 1.0e-6,
    "cautious_alpha": 1.0,
    "rigid_translation_projection": False,
    "deep_qn_diagnostics": False,
    "diagnostic_shift_mus": "0.01 0.1 1 10",
    "dynamic_h0": False,
    # 0 means all pairs generated by the retained state window.  This is
    # deliberately independent of legacy translation_memory.
    "max_pairs": 0,
    # Diagnostic comparison only by default.  The comparison and metrics are
    # still computed by the canonical translator.  ``error`` is retained as a
    # backward-compatible nonfatal alias for ``off`` so already-generated
    # queued configs cannot kill searches.  Only explicit ``fatal`` aborts.
    "projection_validation": "off",
    "projection_validation_tolerance": 1.0e-8,
    "reuse_ablation": True,
    "reconstruction_timing": True,
    "raw_dump": False,
    "raw_dump_directory": "Dimer_history_npzs",
}


_PAIR_SAFEGUARD_ALIASES = {
    "legacy_translation_guard": "damp",
    "legacy_dimer_guard": "damp",
    "shifted_secant": "damp",
}


def _bool(value: object) -> bool:
    if isinstance(value, bool):
        return value
    token = str(value).strip().lower()
    if token in {"1", "true", "yes", "on"}:
        return True
    if token in {"0", "false", "no", "off", "", "none"}:
        return False
    raise ValueError(f"cannot interpret {value!r} as bool")



def _optional_cosine_threshold(value: object) -> float | None:
    token = str(value).strip().lower()
    if token in {"", "off", "none", "false"}:
        return None
    out = float(value)
    if not -1.0 <= out <= 1.0:
        raise ValueError("cosine threshold must lie in [-1, 1] or be off")
    return out

def normalize_history_options(
    options: Mapping[str, object] | None,
    *,
    translation_optimizer: object,
) -> dict[str, object]:
    """Normalize one history configuration without mutating its source."""

    result = dict(DEFAULT_HISTORY_OPTIONS)
    result.update(dict(options or {}))
    translator = str(translation_optimizer).strip().lower()
    result["rotation_reuse"] = _bool(result.get("rotation_reuse", False))
    result["rotation_history_source"] = str(
        result.get("rotation_history_source", "legacy_derived")
    ).strip().lower()
    result["rotation_max_pairs"] = int(result.get("rotation_max_pairs", 0))
    result["rotation_pair_sources"] = " ".join(
        normalise_tokens(result.get("rotation_pair_sources", "consecutive_physical"))
    )
    result["rotation_accepted_force_source"] = str(
        result.get("rotation_accepted_force_source", "physical_only")
    ).strip().lower()
    result["rotation_trial_pairs_future_only"] = _bool(
        result.get("rotation_trial_pairs_future_only", False)
    )
    result["rotation_cosine_threshold"] = _optional_cosine_threshold(
        result.get("rotation_cosine_threshold", "off")
    )
    result["enabled"] = (
        _bool(result.get("enabled", False))
        or translator in {"canonical_lbfgs", "partitioned_lbfgs", "q_lbfgs_dimer_axial"}
        or bool(result["rotation_reuse"])
    )
    result["memory_states"] = int(result["memory_states"])
    result["max_probes_per_state"] = int(result["max_probes_per_state"])
    result["center_tolerance"] = float(result["center_tolerance"])
    result["sample_tolerance"] = float(result["sample_tolerance"])
    result["record_sources"] = " ".join(normalise_tokens(result["record_sources"]))
    result["pair_sources"] = " ".join(normalise_tokens(result["pair_sources"]))
    result["pair_order"] = str(result["pair_order"]).strip().lower()
    result["projection_policy"] = str(result["projection_policy"]).strip().lower()
    result["kappa_projection_policy"] = str(
        result["kappa_projection_policy"]
    ).strip().lower()
    requested = str(result["pair_safeguard"]).strip().lower()
    result["pair_safeguard"] = requested
    result["pair_safeguard_resolved"] = _PAIR_SAFEGUARD_ALIASES.get(
        requested, requested
    )
    result["curvature_floor"] = float(result["curvature_floor"])
    result["curvature_epsilon"] = float(result["curvature_epsilon"])
    result["powell_eta"] = float(result["powell_eta"])
    result["cosine_threshold"] = _optional_cosine_threshold(
        result.get("cosine_threshold", "off")
    )
    result["cautious_epsilon"] = float(result.get("cautious_epsilon", 1.0e-6))
    result["cautious_alpha"] = float(result.get("cautious_alpha", 1.0))
    result["rigid_translation_projection"] = _bool(result.get("rigid_translation_projection", False))
    result["deep_qn_diagnostics"] = _bool(result.get("deep_qn_diagnostics", False))
    result["diagnostic_shift_mus"] = str(result.get("diagnostic_shift_mus", "0.01 0.1 1 10"))
    result["dynamic_h0"] = _bool(result["dynamic_h0"])
    result["max_pairs"] = int(result["max_pairs"])
    requested_projection_validation = str(
        result["projection_validation"]
    ).strip().lower()
    result["projection_validation_requested"] = requested_projection_validation
    # Queue-safe compatibility: historical generated configs frequently contain
    # projection_validation=error.  That development-time behavior is no longer
    # allowed to terminate production searches.  Preserve the key as accepted
    # input but normalize it to silent diagnostic mode.
    result["projection_validation"] = (
        "off" if requested_projection_validation == "error"
        else requested_projection_validation
    )
    result["projection_validation_tolerance"] = float(
        result["projection_validation_tolerance"]
    )
    result["reuse_ablation"] = _bool(result["reuse_ablation"])
    result["reconstruction_timing"] = _bool(result["reconstruction_timing"])
    result["raw_dump"] = _bool(result["raw_dump"])
    result["raw_dump_directory"] = str(result["raw_dump_directory"]).strip()
    validate_history_options(result, translation_optimizer=translator)
    return result


def validate_history_options(
    options: Mapping[str, object],
    *,
    translation_optimizer: object,
) -> None:
    translator = str(translation_optimizer).strip().lower()
    if int(options["memory_states"]) < 1:
        raise ValueError("[ourDimerHistory] memory_states must be >= 1")
    if int(options["max_probes_per_state"]) < 0:
        raise ValueError("[ourDimerHistory] max_probes_per_state must be >= 0")
    if str(options.get("rotation_history_source", "legacy_derived")) not in {
        "force_bank", "legacy_derived"
    }:
        raise ValueError(
            "[ourDimerHistory] rotation_history_source must be force_bank or legacy_derived"
        )
    if int(options.get("rotation_max_pairs", 0)) < 0:
        raise ValueError("[ourDimerHistory] rotation_max_pairs must be >= 0")
    valid_rotation_pair_sources = {
        "consecutive_physical", "fourier_trial", "accepted_rotation", "direct_accepted"
    }
    rotation_pair_sources = set(normalise_tokens(
        options.get("rotation_pair_sources", "consecutive_physical")
    ))
    if not rotation_pair_sources or not rotation_pair_sources <= valid_rotation_pair_sources:
        raise ValueError(
            "[ourDimerHistory] rotation_pair_sources must contain only "
            "consecutive_physical, fourier_trial, accepted_rotation, or direct_accepted"
        )
    if str(options.get("rotation_accepted_force_source", "physical_only")) not in {
        "physical_only", "allow_extrapolated"
    }:
        raise ValueError(
            "[ourDimerHistory] rotation_accepted_force_source must be "
            "physical_only or allow_extrapolated"
        )
    if float(options["center_tolerance"]) < 0.0:
        raise ValueError("[ourDimerHistory] center_tolerance must be >= 0")
    if float(options["sample_tolerance"]) < 0.0:
        raise ValueError("[ourDimerHistory] sample_tolerance must be >= 0")

    record_sources = set(normalise_tokens(options["record_sources"]))
    if not ({"center", "all"} & record_sources):
        raise ValueError(
            "[ourDimerHistory] record_sources must include center or all"
        )
    pair_sources = normalise_tokens(options["pair_sources"])
    if not pair_sources:
        raise ValueError("[ourDimerHistory] pair_sources cannot be empty")
    for token in pair_sources:
        if token == "center_center":
            continue
        if token in {"center_probe_all", "center_all_probes"}:
            if "all" not in record_sources:
                raise ValueError(
                    f"[ourDimerHistory] {token} requires record_sources=all"
                )
            continue
        if token.startswith("center_family:"):
            family = token.split(":", 1)[1].strip()
            if not family:
                raise ValueError(f"empty family in pair source {token!r}")
            if "all" not in record_sources and family not in record_sources:
                raise ValueError(
                    f"[ourDimerHistory] {token!r} requires {family!r} in "
                    "record_sources"
                )
            continue
        if token.startswith("center_source:"):
            source = token.split(":", 1)[1].strip()
            if not source:
                raise ValueError(f"empty source in pair source {token!r}")
            # Exact labels may be future extensions.  Their broad family or
            # the exact source must be recordable; final admission is checked
            # by CanonicalForceHistory.
            family = source.split("_", 1)[0]
            if (
                "all" not in record_sources
                and source not in record_sources
                and family not in record_sources
            ):
                raise ValueError(
                    f"[ourDimerHistory] {token!r} is not enabled by "
                    "record_sources"
                )
            continue
        if token.startswith("center_") and len(token) > len("center_"):
            family = token[len("center_") :]
            if "all" not in record_sources and family not in record_sources:
                raise ValueError(
                    f"[ourDimerHistory] pair source {token!r} requires "
                    f"{family!r} in record_sources"
                )
            continue
        raise ValueError(
            "[ourDimerHistory] pair_sources entries must be center_center, "
            "center_<family>, center_family:<family>, center_source:<source>, "
            f"or center_probe_all; got {token!r}"
        )

    if str(options["pair_order"]) != "acquisition":
        raise ValueError(
            "[ourDimerHistory] only pair_order=acquisition is implemented"
        )
    if options["projection_policy"] != "current_snapshot":
        raise ValueError(
            "[ourDimerHistory] only projection_policy=current_snapshot is implemented"
        )
    if options["kappa_projection_policy"] != "fixed_current_center_coefficients":
        raise ValueError(
            "[ourDimerHistory] only kappa_projection_policy="
            "fixed_current_center_coefficients is implemented"
        )

    safeguard = str(options["pair_safeguard_resolved"])
    if safeguard not in {"off", "skip", "damp", "powell", "reset", "cautious"}:
        raise ValueError(
            "[ourDimerHistory] pair_safeguard must be "
            "legacy_translation_guard, off, skip, damp, powell, reset, or cautious; "
            f"got {options['pair_safeguard']!r}"
        )
    if safeguard in {"skip", "damp", "reset"} and float(
        options["curvature_floor"]
    ) <= 0.0:
        raise ValueError(
            "[ourDimerHistory] curvature_floor must be > 0 for skip/damp/reset"
        )
    if float(options["curvature_epsilon"]) < 0.0:
        raise ValueError("[ourDimerHistory] curvature_epsilon must be >= 0")
    if safeguard == "cautious" and (float(options.get("cautious_epsilon", 1e-6)) <= 0.0 or float(options.get("cautious_alpha", 1.0)) < 0.0):
        raise ValueError("[ourDimerHistory] cautious_epsilon >0 and cautious_alpha >=0 required")
    if safeguard == "powell" and not 0.0 < float(options["powell_eta"]) < 1.0:
        raise ValueError("[ourDimerHistory] powell_eta must satisfy 0 < eta < 1")
    if int(options["max_pairs"]) < 0:
        raise ValueError("[ourDimerHistory] max_pairs must be >= 0")
    if options["projection_validation"] not in {"off", "warn", "fatal"}:
        raise ValueError(
            "[ourDimerHistory] projection_validation must be off, warn, fatal, "
            "or the backward-compatible alias error"
        )
    if float(options["projection_validation_tolerance"]) < 0.0:
        raise ValueError(
            "[ourDimerHistory] projection_validation_tolerance must be >= 0"
        )
    if bool(options["raw_dump"]) and not str(options["raw_dump_directory"]):
        raise ValueError(
            "[ourDimerHistory] raw_dump_directory cannot be empty when raw_dump=True"
        )
    if not _bool(options["reconstruction_timing"]):
        raise ValueError(
            "[ourDimerHistory] reconstruction_timing=False is not supported in "
            "the first benchmark release; timing is required for validation"
        )
    if translator == "canonical_lbfgs" and not _bool(options["enabled"]):
        raise ValueError("canonical_lbfgs requires canonical history to be enabled")
    if bool(options.get("rotation_reuse", False)):
        sources = set(normalise_tokens(options["record_sources"]))
        if "rotation" not in sources and "all" not in sources:
            raise ValueError("canonical rotation reuse requires rotation in record_sources")


def history_options_from_config(
    config_dict: Mapping[str, object],
    *,
    translation_optimizer: object | None = None,
) -> dict[str, object]:
    dimer = dict(config_dict.get("ourDimer", {}) or {})  # type: ignore[arg-type]
    translator = (
        translation_optimizer
        if translation_optimizer is not None
        else dimer.get("translation_optimizer", "ase")
    )
    raw = config_dict.get("ourDimerHistory", {})  # type: ignore[arg-type]
    return normalize_history_options(
        dict(raw or {}), translation_optimizer=translator  # type: ignore[arg-type]
    )



def partitioned_options_from_config(
    config_dict: Mapping[str, object],
    *,
    translation_optimizer: object = "partitioned_lbfgs",
) -> dict[str, object]:
    """Return partitioned-core settings for the legacy or Q+Dimer translator.

    ``partitioned_lbfgs`` preserves the historical P+Q knobs exactly.  The
    capability selector ``q_lbfgs_dimer_axial`` reuses the canonical ForceBank
    pair policy for Q and swaps only the P-step source to direct Dimer curvature.
    """
    translator = str(translation_optimizer).strip().lower()
    if translator not in {"partitioned_lbfgs", "q_lbfgs_dimer_axial"}:
        raise ValueError(f"unsupported partitioned-core translator: {translator!r}")
    cfg = dict(config_dict.get("ourPartitionedLBFGS", {}) or {})
    lbfgs_cfg = dict(config_dict.get("ourDimerLBFGS", {}) or {})
    history_cfg = history_options_from_config(
        config_dict, translation_optimizer=translator
    )
    options = {
        "pair_sources": history_cfg["pair_sources"],
        "projector_policy": str(cfg.get("projector_policy", "reconstruct")).strip().lower(),
        "projector_overlap_tolerance": float(cfg.get("projector_overlap_tolerance", 0.95)),
        "sign_reference_overlap_tolerance": float(cfg.get("sign_reference_overlap_tolerance", 1.0e-10)),
        "p_initial_hessian": float(cfg.get("p_initial_hessian", 70.0)),
        "q_initial_hessian": float(cfg.get("q_initial_hessian", 70.0)),
        "p_dynamic_h0": _bool(cfg.get("p_dynamic_h0", False)),
        "q_dynamic_h0": _bool(cfg.get("q_dynamic_h0", False)),
        "p_safeguard": str(cfg.get("p_safeguard", "skip")).strip().lower(),
        "q_safeguard": str(cfg.get("q_safeguard", "skip")).strip().lower(),
        "p_curvature_floor": float(cfg.get("p_curvature_floor", 1.0e-3)),
        "q_curvature_floor": float(cfg.get("q_curvature_floor", 1.0e-3)),
        "curvature_epsilon": float(cfg.get("curvature_epsilon", 1.0e-12)),
        "powell_eta": float(cfg.get("powell_eta", 0.2)),
        "p_memory": int(cfg.get("p_memory", 10)),
        "q_memory": int(cfg.get("q_memory", 10)),
        "step_damping": float(cfg.get("step_damping", 1.0)),
        # Reuse the existing generic translation-regularization surface.  The
        # partitioned model applies one shared scalar shift to both P/Q blocks;
        # no partition-specific benchmark knob is introduced here.
        "regularization": str(
            lbfgs_cfg.get("translation_regularization", "off")
        ).strip().lower(),
        "regularization_mu": float(
            lbfgs_cfg.get("translation_regularization_mu", 1.0)
        ),
        "regularization_radius": float(
            lbfgs_cfg.get("translation_regularization_radius", 0.1)
        ),
        "regularization_tolerance": float(
            lbfgs_cfg.get("translation_regularization_tolerance", 1.0e-8)
        ),
        "p_step_source": "legacy_lbfgs",
    }
    if translator == "q_lbfgs_dimer_axial":
        # Q uses the canonical ForceBank admission/cap surface so arm-specific
        # memory/safeguard knobs are not duplicated.  Legacy P/Q knobs remain
        # authoritative only for the old partitioned selector.
        options.update({
            "p_step_source": "dimer_curvature",
            "q_dynamic_h0": bool(history_cfg["dynamic_h0"]),
            "q_safeguard": str(history_cfg["pair_safeguard_resolved"]),
            "q_curvature_floor": float(history_cfg["curvature_floor"]),
            "curvature_epsilon": float(history_cfg["curvature_epsilon"]),
            "powell_eta": float(history_cfg["powell_eta"]),
            "q_memory": int(history_cfg["max_pairs"]),
        })
    return options


class _RFOTranslationRuntime:
    """Attempt-scoped runtime for generic physical-B RFO-family translation.

    Fixed RAS is stateless. Adaptive RAS owns only the Sella-2.5.0-parity outer
    trust state and a pending accepted-step model prediction. It never requests
    calculator work; the next already-computed center observation closes the
    pending trust update before the physical-Hessian history is updated.
    """

    STATE_SCHEMA = "saddlemill_rfo_runtime_v2"

    def __init__(self, settings: Mapping[str, object]):
        from saddlemill.dimertools.ras import AdaptiveRASTrustController

        self.settings = dict(settings)
        self.last_pretranslator_snapshot: dict[str, object] | None = None
        self.last_trust_transition: dict[str, object] | None = None
        self._pending_trust: dict[str, object] | None = None
        self._prepared_trust: dict[str, object] | None = None
        self.trust_controller = None
        if str(self.settings.get("trust_policy", "fixed")) == "adaptive":
            self.trust_controller = AdaptiveRASTrustController(
                delta=float(self.settings["trust_radius"]),
                sigma_inc=float(self.settings["trust_sigma_inc"]),
                sigma_dec=float(self.settings["trust_sigma_dec"]),
                rho_inc=float(self.settings["trust_rho_inc"]),
                rho_dec=float(self.settings["trust_rho_dec"]),
                delta_min=float(self.settings["trust_delta_min"]),
            )

    @staticmethod
    def _array_sha256(value: object) -> str:
        array = np.ascontiguousarray(np.asarray(value, dtype=np.float64))
        digest = hashlib.sha256()
        digest.update(str(array.shape).encode("ascii"))
        digest.update(array.dtype.str.encode("ascii"))
        digest.update(array.tobytes(order="C"))
        return digest.hexdigest()

    @staticmethod
    def _mapping_sha256(value: Mapping[str, object]) -> str:
        from saddlemill.dimertools.foundation_types import json_safe

        payload = json.dumps(json_safe(dict(value)), sort_keys=True, separators=(",", ":"))
        return hashlib.sha256(payload.encode("utf-8")).hexdigest()

    @staticmethod
    def _observation_energy(observation) -> float | None:
        metadata = dict(getattr(observation, "metadata", {}) or {})
        for key in ("potential_energy", "energy", "pes_energy"):
            if key not in metadata:
                continue
            try:
                value = float(metadata[key])
            except (TypeError, ValueError):
                continue
            if np.isfinite(value):
                return value
        return None

    @property
    def current_radius(self) -> float | None:
        if str(self.settings.get("step_control")) != "ras":
            return self.settings.get("trust_radius")  # type: ignore[return-value]
        if self.trust_controller is not None:
            return float(self.trust_controller.delta)
        value = self.settings.get("trust_radius")
        return None if value is None else float(value)

    def _snapshot(self, request, *, pre_step_pes_calls: int | None = None) -> dict[str, object]:
        g = np.asarray(request.raw_gradient, dtype=float)
        if request.matrix is not None:
            B = np.asarray(request.matrix, dtype=float)
            evals, evecs = np.linalg.eigh(0.5 * (B + B.T))
            mode = np.asarray(evecs[:, 0], dtype=float)
            model_hash = self._array_sha256(B)
        else:
            learned = np.asarray(request.spectral_eigenvalues, dtype=float).reshape(-1)
            vectors = np.asarray(request.spectral_eigenvectors, dtype=float)
            beta = float(request.spectral_baseline)
            complement = max(0, g.size - learned.size)
            evals = np.sort(np.concatenate((learned, np.full(complement, beta))))
            if learned.size == 0:
                raise RuntimeError("compact_physical_hessian_has_no_learned_lowest_mode")
            mode = np.asarray(vectors[:, 0], dtype=float)
            digest = hashlib.sha256()
            digest.update(np.ascontiguousarray(learned, dtype=np.float64).tobytes())
            digest.update(np.ascontiguousarray(vectors, dtype=np.float64).tobytes())
            digest.update(np.asarray([beta], dtype=np.float64).tobytes())
            model_hash = digest.hexdigest()
        first = np.flatnonzero(np.abs(mode) > 1.0e-14)
        if first.size and mode[int(first[0])] < 0.0:
            mode = -mode
        return {
            "schema": "saddlemill_rfo_pretranslator_snapshot_v2",
            "physical_b_sha256": model_hash,
            "physical_b_spectrum": [float(x) for x in evals],
            "selected_b_mode_sha256": self._array_sha256(mode),
            "selected_b_mode": [float(x) for x in mode],
            "raw_gradient_sha256": self._array_sha256(g),
            "raw_gradient": [float(x) for x in g],
            # Keep the RC1 key additive/backward-readable while exposing the
            # generic architecture terminology.
            "fixed_ras_radius": self.current_radius,
            "ras_requested_radius": self.current_radius,
            "ras_root_solver": self.settings.get("restricted_step_root_solver"),
            "trust_policy": self.settings.get("trust_policy"),
            "coordinate_space_id": request.coordinate_space_id,
            "state_uid": request.state_uid,
            "geometry_id": request.geometry_id,
            "center_observation_id": request.center_observation_id,
            "center_metadata_sha256": self._mapping_sha256(
                dict(getattr(self, "_last_center_metadata", {}) or {})
            ),
            "history_provenance_sha256": self._mapping_sha256(
                dict(getattr(self, "_last_center_provenance", {}) or {})
            ),
            "history_provenance": dict(getattr(self, "_last_center_provenance", {}) or {}),
            "model_update_type": request.model_update_type,
            "model_age": int(request.model_age),
            "pre_step_pes_calls": None if pre_step_pes_calls is None else int(pre_step_pes_calls),
            "t17_added_pes_calls": int(request.t17_added_pes_calls),
        }

    def propose(self, model, center_observation, current_mode=None, *, pre_step_pes_calls=None):
        from saddlemill.dimertools.rfo_translation import build_c2_rfo_input, compute_rfo_translation

        if self._pending_trust is not None:
            raise RuntimeError("adaptive_trust_pending_step_not_evaluated")
        partition = str(self.settings["partition"])
        external_mode = current_mode if partition == "external_mode" else None
        request = build_c2_rfo_input(
            model,
            center_observation,
            external_mode=external_mode,
            expected_model_origin="physical_hessian_model",
            expected_update_type=model.update_type,
            expected_model_age=model.model_age,
            gradient_kind="raw_physical",
            parallel_force_damping="none",
            force_transform="none",
        )
        control = str(self.settings["step_control"])
        self._last_center_metadata = dict(getattr(center_observation, "metadata", {}) or {})
        self._last_center_provenance = {
            "source": str(getattr(center_observation, "source", "")),
            "family": str(getattr(center_observation, "family", "")),
            "role": str(getattr(center_observation, "role", "")),
            "evaluation": str(getattr(center_observation, "evaluation", "")),
            "force_call_delta": int(getattr(center_observation, "force_call_delta", 0)),
            "state_id": int(getattr(center_observation, "state_id", -1)),
            "geometry_id": str(getattr(center_observation, "geometry_id", "")),
        }
        self.last_pretranslator_snapshot = self._snapshot(
            request, pre_step_pes_calls=pre_step_pes_calls
        )
        radius = self.current_radius
        result = compute_rfo_translation(
            request,
            partition=partition,
            step_control=control,
            target_order=int(self.settings["target_order"]),
            physical_root_policy=str(self.settings["physical_root_policy"]),
            physical_homing_mode=(current_mode if str(self.settings["physical_root_policy"]) == "homed" else None),
            negative_mode_policy=str(self.settings["negative_mode_policy"]),
            negative_tolerance=float(self.settings["negative_tolerance"]),
            physical_degeneracy_tolerance=float(self.settings["physical_degeneracy_tolerance"]),
            external_coupling_tolerance=float(self.settings["external_coupling_tolerance"]),
            norm_cap=(self.settings["norm_cap"] if control == "norm_cap" else None),
            trust_radius=(
                radius
                if control in {"restricted_prfo", "sella_fixed_ras", "sella_qn_fixed_ras", "ras"}
                else None
            ),
            restricted_tolerance=float(self.settings["restricted_tolerance"]),
            restricted_max_iterations=int(self.settings["restricted_max_iterations"]),
            restricted_alpha_min=float(self.settings["restricted_alpha_min"]),
            ras_root_solver=str(self.settings.get("restricted_step_root_solver", "bisection")),
            ras_tolerance=self.settings.get("ras_tolerance", None),
            ras_max_iterations=int(self.settings.get("ras_max_iterations", 1000)),
            translation_step_method=str(self.settings.get("translation_optimizer", "prfo")),
            sella_ras_tolerance=self.settings["sella_ras_tolerance"],
            sella_ras_max_iterations=int(self.settings["sella_ras_max_iterations"]),
            sella_qn_curvature_regularization=float(self.settings["sella_qn_curvature_regularization"]),
            final_safety_cap=None,
            denominator_tolerance=float(self.settings["denominator_tolerance"]),
            root_cluster_tolerance=float(self.settings["root_cluster_tolerance"]),
            matrix_symmetry_tolerance=float(self.settings["matrix_symmetry_tolerance"]),
        )
        if (
            control == "ras"
            and str(self.settings.get("trust_policy")) == "adaptive"
            and result.success
            and result.cartesian_step is not None
        ):
            start_energy = self._observation_energy(center_observation)
            if start_energy is None:
                raise RuntimeError(
                    "AMBIGUOUS_REQUIRES_SCIENTIFIC_DECISION:"
                    "potential_energy_not_available_without_extra_pes_call"
                )
            self._pending_trust = {
                "schema": "saddlemill_adaptive_ras_pending_v1",
                "start_energy": float(start_energy),
                "matrix": (None if request.matrix is None else np.asarray(request.matrix, dtype=float).tolist()),
                "spectral_baseline": request.spectral_baseline,
                "spectral_eigenvalues": (None if request.spectral_eigenvalues is None else np.asarray(request.spectral_eigenvalues, dtype=float).tolist()),
                "spectral_eigenvectors": (None if request.spectral_eigenvectors is None else np.asarray(request.spectral_eigenvectors, dtype=float).tolist()),
                "gradient": np.asarray(request.raw_gradient, dtype=float).tolist(),
                "coordinate_space": request.coordinate_space.to_state_dict(),
                "from_state_uid": request.state_uid,
                "from_geometry_id": request.geometry_id,
                "from_model_age": int(request.model_age),
                "requested_radius": float(radius),
                "boundary_active": bool(result.restricted_boundary_active),
                "solver_achieved_radius": (
                    None
                    if result.restricted_metadata is None
                    else result.restricted_metadata.get("achieved_radius")
                ),
                "applied_reduced_step": None,
                "applied_step_magnitude": None,
            }
        return result

    def note_applied_step(self, cartesian_step: object) -> None:
        if self._pending_trust is None:
            return
        from saddlemill.dimertools.foundation_types import ActiveCoordinateSpace
        from saddlemill.dimertools.ras import restricted_atomic_constraint
        from saddlemill.dimertools.rfo_translation import _CoordinateAdapter

        step = np.asarray(cartesian_step, dtype=float)
        space = ActiveCoordinateSpace.from_state_dict(
            dict(self._pending_trust["coordinate_space"])
        )
        adapter = _CoordinateAdapter(space)
        reduced = adapter.reduce(step)
        magnitude = float(restricted_atomic_constraint(step.reshape(-1)))
        self._pending_trust["applied_reduced_step"] = reduced.tolist()
        self._pending_trust["applied_step_magnitude"] = magnitude
        self._pending_trust["applied_cartesian_step_sha256"] = self._array_sha256(step)

    def prepare_evaluated_center(self, center_observation) -> None:
        """Prepare the post-step energy ratio without mutating trust state.

        Sella 2.5.0 ``PES.kick`` evaluates the new energy/gradient, forms the
        actual/predicted ratio, then updates its Hessian before the optimizer
        mutates ``delta``.  SaddleMill mirrors that ordering by preparing the
        ratio here, letting the shared physical TS-BFGS model consume the new
        center, and applying the radius transition only in
        :meth:`finalize_evaluated_center_trust`.
        """
        if self._pending_trust is None:
            return
        state_uid = f"state{int(center_observation.state_id)}:{center_observation.geometry_id}"
        if state_uid == str(self._pending_trust["from_state_uid"]):
            return
        if self.trust_controller is None:
            raise RuntimeError("adaptive_trust_controller_missing")
        if self._pending_trust.get("applied_reduced_step") is None:
            raise RuntimeError("adaptive_trust_applied_step_not_recorded")
        end_energy = self._observation_energy(center_observation)
        if end_energy is None:
            raise RuntimeError(
                "AMBIGUOUS_REQUIRES_SCIENTIFIC_DECISION:"
                "potential_energy_not_available_without_extra_pes_call"
            )
        from saddlemill.dimertools.ras import AdaptiveRASTrustController

        g = np.asarray(self._pending_trust["gradient"], dtype=float)
        dx = np.asarray(self._pending_trust["applied_reduced_step"], dtype=float)
        if self._pending_trust.get("matrix") is not None:
            B = np.asarray(self._pending_trust["matrix"], dtype=float)
            predicted = AdaptiveRASTrustController.predicted_change(g, B, dx)
        else:
            beta = float(self._pending_trust["spectral_baseline"])
            evals = np.asarray(self._pending_trust["spectral_eigenvalues"], dtype=float)
            evecs = np.asarray(self._pending_trust["spectral_eigenvectors"], dtype=float)
            projected = evecs.T @ dx if evals.size else np.empty(0, dtype=float)
            bdx = beta * dx
            if evals.size:
                bdx = bdx + evecs @ ((evals - beta) * projected)
            predicted = float(np.dot(g, dx) + 0.5 * np.dot(dx, bdx))
        actual = float(end_energy) - float(self._pending_trust["start_energy"])
        self._prepared_trust = {
            "actual_change": actual,
            "predicted_change": predicted,
            "step_magnitude": float(self._pending_trust["applied_step_magnitude"]),
            "from_state_uid": str(self._pending_trust["from_state_uid"]),
            "to_state_uid": state_uid,
            "from_model_age": int(self._pending_trust["from_model_age"]),
        }

    def finalize_evaluated_center_trust(self) -> None:
        """Apply a prepared adaptive-radius transition after physical-B update."""
        if self._prepared_trust is None:
            return
        if self.trust_controller is None:
            raise RuntimeError("adaptive_trust_controller_missing")
        prepared = dict(self._prepared_trust)
        transition = self.trust_controller.update(
            actual_change=float(prepared["actual_change"]),
            predicted_change=float(prepared["predicted_change"]),
            step_magnitude=float(prepared["step_magnitude"]),
        )
        transition.update(
            {
                "from_state_uid": str(prepared["from_state_uid"]),
                "to_state_uid": str(prepared["to_state_uid"]),
                "from_model_age": int(prepared["from_model_age"]),
                "ordering": (
                    "new_center_energy_gradient -> physical_hessian_update -> "
                    "trust_radius_update -> next_step"
                ),
                "restricted_step_type": "ras",
                "root_solver": str(self.settings.get("restricted_step_root_solver", "bisection")),
            }
        )
        self.last_trust_transition = transition
        self._prepared_trust = None
        self._pending_trust = None

    # Compatibility spelling for internal callers from early Worker-D drafts.
    def observe_evaluated_center(self, center_observation) -> None:
        self.prepare_evaluated_center(center_observation)

    def resolved_metadata(self) -> dict[str, object]:
        result = dict(self.settings)
        result["current_trust_radius"] = self.current_radius
        return result

    def restore_state(self, saved: Mapping[str, object]) -> None:
        from saddlemill.dimertools.ras import AdaptiveRASTrustController

        state = dict(saved)
        if state.get("schema") == "saddlemill_rfo_runtime_v1":
            # RC1 fixed-radius runtime had no mutable scientific state.
            comparable = {k: state.get(k) for k in self.settings if k in state}
            for key, value in comparable.items():
                if self.settings.get(key) != value:
                    raise ValueError("resume RFO runtime configuration mismatch")
            return
        if state.get("schema") != self.STATE_SCHEMA:
            raise ValueError("unsupported RFO runtime state schema")
        saved_settings = dict(state.get("settings", {}) or {})
        if saved_settings != self.settings:
            raise ValueError("resume RFO runtime state does not match resolved configuration")
        trust_state = state.get("adaptive_trust")
        if trust_state is not None:
            if self.trust_controller is None:
                raise ValueError("resume contains adaptive trust for fixed-trust configuration")
            self.trust_controller = AdaptiveRASTrustController.from_state_dict(dict(trust_state))
        elif self.trust_controller is not None:
            raise ValueError("resume missing adaptive trust state")
        self.last_trust_transition = (
            None if state.get("last_trust_transition") is None
            else dict(state["last_trust_transition"])
        )
        self._pending_trust = (
            None if state.get("pending_trust") is None else dict(state["pending_trust"])
        )
        self._prepared_trust = (
            None if state.get("prepared_trust") is None else dict(state["prepared_trust"])
        )

    def state_dict(self) -> dict[str, object]:
        return {
            "schema": self.STATE_SCHEMA,
            "settings": dict(self.settings),
            "trust_policy": str(self.settings.get("trust_policy", "fixed")),
            "adaptive_trust": (
                None if self.trust_controller is None else self.trust_controller.state_dict()
            ),
            "last_trust_transition": self.last_trust_transition,
            "pending_trust": self._pending_trust,
            "prepared_trust": self._prepared_trust,
        }


def create_rfo_translation_runtime(config_dict: Mapping[str, object]):
    """Create the generic physical-B RFO/QN/P-RFO translation runtime."""
    from saddlemill.dimertools.ras import (
        RAS_DEFAULT_MAXITER,
        SELLA_SADDLE_DELTA0,
        SELLA_SADDLE_ETA,
        SELLA_SADDLE_RHO_DEC,
        SELLA_SADDLE_RHO_INC,
        SELLA_SADDLE_SIGMA_DEC,
        SELLA_SADDLE_SIGMA_INC,
    )

    dimer = dict(config_dict.get("ourDimer", {}) or {})
    ph = dict(config_dict.get("ourPhysicalHessian", {}) or {})
    ms = dict(config_dict.get("ourModeSchedule", {}) or {})
    cfg = dict(config_dict.get("ourRFO", {}) or {})
    optimizer = str(dimer.get("translation_optimizer", "ase")).strip().lower()
    if optimizer not in {"rfo", "prfo", "qn_mmf"}:
        raise ValueError("create_rfo_translation_runtime requires translation_optimizer=rfo, prfo, or qn_mmf")
    if str(ph.get("update", "off")).strip().lower() == "off":
        raise ValueError("RFO/P-RFO/QN-MMF translation requires a non-off physical Hessian B model")
    if str(ms.get("parallel_force_damping", "none")).strip().lower() != "none":
        raise ValueError("RFO/P-RFO/QN-MMF translation requires parallel_force_damping=none")
    raw_partition = cfg.get("partition", None)
    raw_control = cfg.get("step_control", None)
    if raw_partition in (None, "", "none", "None"):
        raise ValueError("[ourRFO] partition must be selected explicitly")
    if raw_control in (None, "", "none", "None"):
        raise ValueError("[ourRFO] step_control must be selected explicitly")
    partition = str(raw_partition).strip().lower()
    control = str(raw_control).strip().lower()

    if optimizer == "rfo" and partition not in {"unpartitioned_order0", "unpartitioned_order1"}:
        raise ValueError("translation_optimizer=rfo requires an unpartitioned RFO partition")
    if optimizer == "prfo" and partition not in {"physical_b_eigen", "external_mode"}:
        raise ValueError("translation_optimizer=prfo requires physical_b_eigen or external_mode partition")
    if optimizer == "qn_mmf" and partition != "physical_b_eigen":
        raise ValueError("translation_optimizer=qn_mmf requires physical_b_eigen partition")
    if control == "restricted_prfo" and optimizer != "prfo":
        raise ValueError("restricted_prfo step control requires translation_optimizer=prfo")
    if control == "restricted_prfo" and partition not in {"physical_b_eigen", "external_mode"}:
        raise ValueError("restricted_prfo requires a partitioned P-RFO definition")
    if control == "sella_fixed_ras" and optimizer != "prfo":
        raise ValueError("legacy sella_fixed_ras requires translation_optimizer=prfo")
    if control == "sella_qn_fixed_ras" and optimizer != "qn_mmf":
        raise ValueError("legacy sella_qn_fixed_ras requires translation_optimizer=qn_mmf")
    if control in {"sella_fixed_ras", "sella_qn_fixed_ras"} and partition != "physical_b_eigen":
        raise ValueError("legacy Sella-parity fixed RAS controls require physical_b_eigen partition")
    if control == "ras":
        if optimizer == "rfo" and partition != "unpartitioned_order1":
            raise ValueError("generic order-1 RFO RAS requires partition=unpartitioned_order1")
        if optimizer == "prfo" and partition not in {"physical_b_eigen", "external_mode"}:
            raise ValueError("generic P-RFO RAS requires partition=physical_b_eigen or external_mode")
        if optimizer == "qn_mmf" and partition != "physical_b_eigen":
            raise ValueError("generic QN-MMF RAS requires partition=physical_b_eigen")
    if control not in {"unrestricted", "norm_cap", "restricted_prfo", "ras", "sella_fixed_ras", "sella_qn_fixed_ras"}:
        raise ValueError("unsupported [ourRFO] step_control")
    representation = str(ph.get("representation", "online_dense")).strip().lower().replace("-", "_")
    if representation == "forcebank_window_compact" and (optimizer != "qn_mmf" or control != "ras"):
        raise ValueError("forcebank_window_compact requires translation_optimizer=qn_mmf with [ourRFO] step_control=ras")

    target_order = int(cfg.get("target_order", 1))
    if target_order != 1:
        raise ValueError("current generic RFO-family runtime supports target_order=1 only")
    physical_root_policy = str(cfg.get("physical_root_policy", "lowest")).strip().lower()
    if physical_root_policy not in {"lowest", "homed"}:
        raise ValueError("[ourRFO] physical_root_policy must be lowest or homed")
    if (
        control in {"ras", "sella_fixed_ras", "sella_qn_fixed_ras"}
        and optimizer in {"prfo", "qn_mmf"}
        and partition == "physical_b_eigen"
        and physical_root_policy != "lowest"
    ):
        raise ValueError("physical-B RAS variants require physical_root_policy=lowest")

    trust_policy = str(cfg.get("trust_policy", "fixed")).strip().lower()
    if trust_policy not in {"fixed", "adaptive"}:
        raise ValueError("[ourRFO] trust_policy must be fixed or adaptive")
    if control != "ras" and trust_policy != "fixed":
        raise ValueError("adaptive trust_policy is supported only with step_control=ras")
    root_solver = str(cfg.get("restricted_step_root_solver", "bisection")).strip().lower()
    if control == "ras" and root_solver != "bisection":
        raise ValueError("generic RAS currently requires restricted_step_root_solver=bisection")

    trust_radius = cfg.get("trust_radius", None)
    norm_cap = cfg.get("norm_cap", None)
    trust_radius = None if trust_radius in (None, "", "none", "None") else float(trust_radius)
    norm_cap = None if norm_cap in (None, "", "none", "None") else float(norm_cap)
    if control == "ras" and trust_radius is None:
        trust_radius = float(SELLA_SADDLE_DELTA0) if trust_policy == "adaptive" else None
    if control in {"restricted_prfo", "ras", "sella_fixed_ras", "sella_qn_fixed_ras"} and (trust_radius is None or trust_radius <= 0.0):
        raise ValueError(f"{control} requires positive trust_radius")
    if control == "norm_cap" and (norm_cap is None or norm_cap <= 0.0):
        raise ValueError("norm_cap step control requires positive norm_cap")

    ras_tol_raw = cfg.get("ras_tolerance", None)
    ras_tolerance = None if ras_tol_raw in (None, "", "none", "None") else float(ras_tol_raw)
    settings = {
        "translation_optimizer": optimizer,
        "partition": partition,
        "step_control": control,
        "target_order": 1,
        "physical_root_policy": physical_root_policy,
        "negative_mode_policy": str(cfg.get("negative_mode_policy", "allow")).strip().lower(),
        "trust_policy": trust_policy,
        "trust_radius": trust_radius,
        "restricted_step_root_solver": root_solver,
        "ras_tolerance": ras_tolerance,
        "ras_max_iterations": int(cfg.get("ras_max_iterations", RAS_DEFAULT_MAXITER)),
        "trust_sigma_inc": float(cfg.get("trust_sigma_inc", SELLA_SADDLE_SIGMA_INC)),
        "trust_sigma_dec": float(cfg.get("trust_sigma_dec", SELLA_SADDLE_SIGMA_DEC)),
        "trust_rho_inc": float(cfg.get("trust_rho_inc", SELLA_SADDLE_RHO_INC)),
        "trust_rho_dec": float(cfg.get("trust_rho_dec", SELLA_SADDLE_RHO_DEC)),
        "trust_delta_min": float(cfg.get("trust_delta_min", SELLA_SADDLE_ETA)),
        "norm_cap": norm_cap,
        "negative_tolerance": float(cfg.get("negative_tolerance", 1.0e-12)),
        "physical_degeneracy_tolerance": float(cfg.get("physical_degeneracy_tolerance", 1.0e-10)),
        "external_coupling_tolerance": float(cfg.get("external_coupling_tolerance", 1.0e-6)),
        "restricted_tolerance": float(cfg.get("restricted_tolerance", 1.0e-10)),
        "restricted_max_iterations": int(cfg.get("restricted_max_iterations", 100)),
        "restricted_alpha_min": float(cfg.get("restricted_alpha_min", 1.0e-12)),
        # Legacy compatibility settings; generic RAS does not consume them.
        "sella_ras_tolerance": (
            None if cfg.get("sella_ras_tolerance", None) in (None, "", "none", "None")
            else float(cfg.get("sella_ras_tolerance"))
        ),
        "sella_ras_max_iterations": int(cfg.get("sella_ras_max_iterations", 1000)),
        "sella_qn_curvature_regularization": float(cfg.get("sella_qn_curvature_regularization", 1.0e-12)),
        "denominator_tolerance": float(cfg.get("denominator_tolerance", 1.0e-12)),
        "root_cluster_tolerance": float(cfg.get("root_cluster_tolerance", 1.0e-10)),
        "matrix_symmetry_tolerance": float(cfg.get("matrix_symmetry_tolerance", 1.0e-12)),
    }
    return _RFOTranslationRuntime(settings)


def select_minmode_atoms_class(*, mmf_variant: object, history_enabled: bool):
    from saddlemill.dimertools.minmode_atoms import (
        CanonicalHistoryKappaMinModeAtoms,
        CanonicalHistoryMinModeAtoms,
        ConfigurableRotationMinModeAtoms,
        KappaMinModeAtoms,
    )

    kappa = str(mmf_variant).strip().lower() == "kappa"
    if history_enabled:
        return CanonicalHistoryKappaMinModeAtoms if kappa else CanonicalHistoryMinModeAtoms
    return KappaMinModeAtoms if kappa else ConfigurableRotationMinModeAtoms


def select_translation_optimizer_class(name: object):
    token = str(name).strip().lower()
    try:
        from saddlemill.dimertools.translation_optimizers import (
            CanonicalHistoryLBFGSMinModeTranslate,
            DiagnosticMinModeTranslate,
            HybridMinModeTranslate,
            LBFGSMinModeTranslate,
            PartitionedLBFGSMinModeTranslate,
            RFOPRFOMinModeTranslate,
        )
    except ModuleNotFoundError as exc:
        if exc.name != "ase":
            raise
        # Dependency-light contract collection can still resolve the legacy
        # selector name. Real construction remains impossible without ASE.
        class DiagnosticMinModeTranslate:  # type: ignore[no-redef]
            pass
        class LBFGSMinModeTranslate:  # type: ignore[no-redef]
            pass
        class HybridMinModeTranslate:  # type: ignore[no-redef]
            pass
        class CanonicalHistoryLBFGSMinModeTranslate:  # type: ignore[no-redef]
            pass
        class PartitionedLBFGSMinModeTranslate:  # type: ignore[no-redef]
            pass
        class RFOPRFOMinModeTranslate:  # type: ignore[no-redef]
            pass

    if token == "ase":
        return DiagnosticMinModeTranslate
    if token == "lbfgs":
        return LBFGSMinModeTranslate
    if token in {"hybrid", "fire_lbfgs"}:
        return HybridMinModeTranslate
    if token == "canonical_lbfgs":
        return CanonicalHistoryLBFGSMinModeTranslate
    if token in {"partitioned_lbfgs", "q_lbfgs_dimer_axial"}:
        return PartitionedLBFGSMinModeTranslate
    if token in {"rfo", "prfo", "qn_mmf"}:
        return RFOPRFOMinModeTranslate
    if token in {"generic_good_broyden", "johnson_modified_broyden"}:
        from saddlemill.dimertools.wave_b_translation import BroydenMinModeTranslate
        return BroydenMinModeTranslate
    raise ValueError(f"unsupported translation optimizer: {token!r}")


def create_dimer_search(
    atoms,
    calc,
    eigenmode=None,
    displacement_dict=None,
    dimer_control_kwargs=None,
    control_logfile=None,
    mode_logfile=None,
    logfile=None,
    trajectory=None,
    engine="ase",
    min_mode_finder="dimer",
    mmf_variant="standard",
    mode_reuse="none",
    convex_escape="standard",
    bowl_active_atoms=20,
    minmode_options=None,
    initial_hessian_matrix=None,
    kappa_kwargs=None,
    kappa_control_kwargs=None,
    rotation_optimizer="ase",
    translation_optimizer="ase",
    rotation_lbfgs_options=None,
    translation_lbfgs_options=None,
    hybrid_options=None,
    history_options=None,
    wave_b_options=None,
    partitioned_lbfgs_options=None,
    rfo_runtime=None,
    runtime_state=None,
    attempt_rng=None,
):
    """Create the selected MMF state and translator without running them.

    For every legacy selector this reproduces the previous ``_setup_dimer``
    construction.  Canonical recording is introduced only when history is
    explicitly enabled or ``translation_optimizer=canonical_lbfgs``.
    """

    from saddlemill.dimertools.kappa_dimer import IsolatedDimerControl

    atoms.calc = calc
    eig_kw = {"eigenmodes": [np.array(eigenmode)]} if eigenmode is not None else {}
    engine = str(engine).lower()
    min_mode_finder = str(min_mode_finder).lower()
    mmf_variant = str(mmf_variant).lower()
    mode_reuse = str(mode_reuse).lower()
    convex_escape = str(convex_escape).lower()
    rotation_optimizer = str(rotation_optimizer).lower()
    translation_optimizer = str(translation_optimizer).lower()

    # Preserve legacy engine aliases exactly.  Composable selectors apply only
    # to the explicit engine=mmf path.
    if engine == "ase":
        min_mode_finder = "dimer"
        mmf_variant = "standard"
        mode_reuse = "none"
        convex_escape = "standard"
    elif engine == "kappa":
        min_mode_finder = "dimer"
        mmf_variant = "kappa"
        mode_reuse = "none"
        convex_escape = "standard"
    elif engine != "mmf":
        raise ValueError(
            f"Unknown MMF engine={engine!r}; expected ase, kappa, or mmf."
        )

    # projected-Olsen/JD fail-closed HVP semantics are validated at construction too, so
    # direct factory users cannot create an invalid public solver selector.
    if min_mode_finder in {
        "lanczos", "davidson", "softsaddle_lanczos",
        "softsaddle_davidson", "softsaddle_davidson_textbook", "olsen_jd",
    }:
        mm = dict(minmode_options or {})
        hvp_origin = str(mm.get("hvp_origin", "physical_fd")).strip().lower()
        if hvp_origin == "effective_force_jacobian":
            raise ValueError(
                "hvp_origin=effective_force_jacobian is not a physical HVP backend"
            )
        if hvp_origin not in {
            "physical_fd", "explicit_physical_matrix", "approximate_physical_model"
        }:
            raise ValueError(
                "hvp_origin must be physical_fd, explicit_physical_matrix, or "
                "approximate_physical_model"
            )
        root_policy = str(mm.get("root_policy", "lowest")).strip().lower()
        if root_policy not in {"lowest", "homed_overlap"}:
            raise ValueError("root_policy must be lowest or homed_overlap")
        if float(mm.get("residual_tolerance", 1.0e-3)) < 0.0:
            raise ValueError("residual_tolerance must be >= 0")
        restart = mm.get("olsen_restart_dimension", None)
        if restart not in (None, "", "none", "None") and int(restart) < 2:
            raise ValueError("olsen_restart_dimension must be >= 2 or blank")

    normalized_wave_b = dict(wave_b_options or {})
    from saddlemill.dimertools.wave_b_runtime import wave_b_recording_required
    raw_history = dict(history_options or {})
    if wave_b_recording_required(normalized_wave_b):
        raw_history["enabled"] = True
        sources = list(normalise_tokens(raw_history.get("record_sources", DEFAULT_HISTORY_OPTIONS["record_sources"])))
        if "center" not in sources:
            sources.append("center")
        if str(dict(normalized_wave_b.get("isopotential", {}) or {}).get("selector", "off")) != "off" and "isopotential" not in sources:
            sources.append("isopotential")
        raw_history["record_sources"] = " ".join(sources)
    normalized_history = normalize_history_options(
        raw_history, translation_optimizer=translation_optimizer
    )
    history_enabled = bool(normalized_history["enabled"])
    force_evaluator = None
    if runtime_state is not None and history_enabled:
        from saddlemill.dimertools.runtime_state import restore_force_evaluator
        force_evaluator = restore_force_evaluator(runtime_state)
    if bool(normalized_history.get("rotation_reuse", False)):
        if rotation_optimizer != "lbfgs":
            raise ValueError("[ourDimerHistory] rotation_reuse=True requires rotation_optimizer=lbfgs")
        if min_mode_finder != "dimer":
            raise ValueError("[ourDimerHistory] rotation_reuse=True currently requires min_mode_finder=dimer")
        if mmf_variant != "standard":
            raise ValueError("[ourDimerHistory] rotation_reuse=True currently requires mmf_variant=standard")
    minmode_class = select_minmode_atoms_class(
        mmf_variant=mmf_variant, history_enabled=history_enabled
    )
    history_kw = (
        {"history_options": normalized_history, "force_evaluator": force_evaluator}
        if history_enabled else {}
    )
    ase_random_seed_kw = {}
    if attempt_rng is not None:
        # ASE MinModeAtoms owns a private RandomState.  Seeding NumPy's global
        # generator around construction/displacement cannot control that state;
        # pass the attempt-keyed seed explicitly so Gaussian displacement is
        # deterministic and execution-order invariant.
        ase_random_seed_kw["random_seed"] = int(
            attempt_rng.substream_provenance(
                "ase_candidate_displacement"
            )["legacy_numpy_seed_uint32"]
        )

    if mmf_variant == "kappa":
        d_control = IsolatedDimerControl(
            logfile=control_logfile,
            eigenmode_logfile=mode_logfile,
            **(dimer_control_kwargs or {}),
        )
        kw = dict(kappa_kwargs or {})
        kw.update(
            {
                "rotation_optimizer": rotation_optimizer,
                "rotation_lbfgs_options": rotation_lbfgs_options or {},
                "convex_escape": convex_escape,
                "bowl_active_atoms": int(bowl_active_atoms),
            }
        )
        if kappa_control_kwargs:
            kw["kappa_control"] = IsolatedDimerControl(
                logfile=control_logfile, **kappa_control_kwargs
            )
        if attempt_rng is None:
            d_atoms = minmode_class(
                atoms,
                control=d_control,
                **eig_kw,
                **kw,
                **history_kw,
                **ase_random_seed_kw,
            )
        else:
            with attempt_rng.global_compatibility("external_minmode_setup"):
                d_atoms = minmode_class(
                    atoms,
                    control=d_control,
                    **eig_kw,
                    **kw,
                    **history_kw,
                    **ase_random_seed_kw,
                )
    elif mmf_variant == "standard":
        d_control = IsolatedDimerControl(
            logfile=control_logfile,
            eigenmode_logfile=mode_logfile,
            **(dimer_control_kwargs or {}),
        )
        minmode_kwargs = dict(
            control=d_control,
            rotation_optimizer=rotation_optimizer,
            rotation_lbfgs_options=rotation_lbfgs_options or {},
            min_mode_finder=min_mode_finder,
            minmode_options=minmode_options or {},
            mode_reuse=mode_reuse,
            convex_escape=convex_escape,
            bowl_active_atoms=int(bowl_active_atoms),
            initial_hessian_matrix=initial_hessian_matrix,
            **eig_kw,
            **history_kw,
        )
        if attempt_rng is None:
            d_atoms = minmode_class(
                atoms, **minmode_kwargs, **ase_random_seed_kw
            )
        else:
            with attempt_rng.global_compatibility("external_minmode_setup"):
                d_atoms = minmode_class(
                    atoms, **minmode_kwargs, **ase_random_seed_kw
                )
    else:
        raise ValueError(
            f"Unknown [ourDimer] mmf_variant={mmf_variant!r}; expected "
            "'standard' or 'kappa'."
        )

    # Attempt-keyed RNG is execution identity, not optimizer state. It is
    # attached only so rare SaddleMill-owned stochastic fallbacks inside mode
    # finders can use named local substreams without consulting global RNG.
    d_atoms._saddlemill_attempt_rng = attempt_rng

    d_atoms.wave_b_options = normalized_wave_b
    from saddlemill.dimertools.wave_b_runtime import WaveBRuntimeController
    wave_state = None if runtime_state is None else runtime_state.get("wave_b_runtime")
    d_atoms.wave_b_runtime = WaveBRuntimeController.from_state_dict(normalized_wave_b, wave_state)
    if runtime_state is not None:
        for attr, key in (
            ("_wave_b_cg_by_root", "wave_b_cg_by_root"),
            ("_wave_b_rotation_broyden_by_root", "wave_b_rotation_broyden_by_root"),
            ("_wave_b_translation_broyden_state", "wave_b_translation_broyden_state"),
        ):
            if key in runtime_state:
                setattr(d_atoms, attr, runtime_state[key])

    if runtime_state is not None and history_enabled:
        from saddlemill.dimertools.runtime_state import restore_rotation_histories
        restore_rotation_histories(
            d_atoms, runtime_state, history_options=normalized_history,
            rotation_lbfgs_options=rotation_lbfgs_options or {},
        )

    if displacement_dict:
        if attempt_rng is None:
            d_atoms.displace(**displacement_dict)
        else:
            # ASE owns Gaussian displacement generation for mask/gauss_std
            # dictionaries. Isolate its module-global RNG without changing its
            # distribution or implementation. Explicit-vector dictionaries are
            # harmlessly executed under the same scoped state.
            with attempt_rng.global_compatibility("ase_candidate_displacement"):
                d_atoms.displace(**displacement_dict)
    else:
        if attempt_rng is None:
            tiny = np.random.randn(len(atoms), 3) * 1e-10
        else:
            tiny = (
                attempt_rng.numpy("candidate_tiny_displacement")
                .standard_normal((len(atoms), 3)) * 1e-10
            )
        d_atoms.displace(
            displacement_vector=tiny,
            method="vector",
        )

    common = dict(trajectory=trajectory, logfile=logfile)
    translator_class = select_translation_optimizer_class(translation_optimizer)
    if translation_optimizer == "ase":
        dim_rlx = translator_class(d_atoms, **common)
    elif translation_optimizer == "lbfgs":
        dim_rlx = translator_class(
            d_atoms, lbfgs_options=translation_lbfgs_options or {}, **common
        )
    elif translation_optimizer in {"hybrid", "fire_lbfgs"}:
        dim_rlx = translator_class(
            d_atoms,
            lbfgs_options=translation_lbfgs_options or {},
            hybrid_options=hybrid_options or {},
            **common,
        )
    elif translation_optimizer == "canonical_lbfgs":
        dim_rlx = translator_class(
            d_atoms,
            lbfgs_options=translation_lbfgs_options or {},
            history_options=normalized_history,
            **common,
        )
    elif translation_optimizer in {"partitioned_lbfgs", "q_lbfgs_dimer_axial"}:
        dim_rlx = translator_class(
            d_atoms,
            partitioned_options=partitioned_lbfgs_options or {},
            runtime_state=runtime_state,
            **common,
        )
    elif translation_optimizer in {"rfo", "prfo", "qn_mmf"}:
        if rfo_runtime is None:
            raise ValueError("rfo/prfo/qn_mmf translation requires create_rfo_translation_runtime(config_dict)")
        dim_rlx = translator_class(
            d_atoms, rfo_runtime=rfo_runtime, runtime_state=runtime_state, **common
        )
    elif translation_optimizer in {"generic_good_broyden", "johnson_modified_broyden"}:
        dim_rlx = translator_class(
            d_atoms, family=translation_optimizer,
            broyden_options=dict(normalized_wave_b.get("broyden", {}) or {}),
            **common,
        )
    else:  # pragma: no cover - select_translation_optimizer_class already guards
        raise ValueError(f"unsupported translation optimizer: {translation_optimizer!r}")

    # Additive introspection only; legacy translator numerics do not consult it.
    d_atoms.canonical_history_record_only = bool(
        history_enabled and translation_optimizer not in {
            "canonical_lbfgs", "partitioned_lbfgs", "q_lbfgs_dimer_axial"
        }
    )
    dim_rlx.canonical_history_record_only = d_atoms.canonical_history_record_only
    return d_atoms, dim_rlx


class ModeDiagnosticsRuntime:
    """shared-runtime-owned shared wrapper around mode-diagnostics observational mathematics.

    The wrapper owns configuration, provenance/accounting routing and JSON-safe
    state/status presentation only.  mode-diagnostics continues to own all residual/gap,
    refresh-criterion, reference and hindsight numerical definitions.
    """

    STATE_SCHEMA = "saddlemill_mode_diagnostics_runtime_v1"

    def __init__(self, config, *, coordinate_space, accounting, physical_hessian_model=None):
        from saddlemill.dimertools.mode_diagnostics import MODE_DIAGNOSTIC_SCHEMA
        self.config = dict(config)
        self.coordinate_space = coordinate_space
        self.accounting = accounting
        self.physical_hessian_model = physical_hessian_model
        self.mode_diagnostic_schema = MODE_DIAGNOSTIC_SCHEMA
        self._last_record = None
        self._last_decision = None
        self._last_promotion = {}
        self._last_reference = None
        self._last_reference_noninterference = None

    def resolved_metadata(self):
        return {
            "schema": self.STATE_SCHEMA,
            "enabled": True,
            "criterion": self.config["mode_refresh_criterion"],
            "mode_residual_threshold": self.config.get("mode_residual_threshold"),
            "mode_angular_error_threshold_degrees": self.config.get("mode_angular_error_threshold_degrees"),
            "comparison_tolerance": self.config["comparison_tolerance"],
            "residual_epsilon": self.config["residual_epsilon"],
            "gap_tolerance": self.config["gap_tolerance"],
            "model_gap_solver_tolerance": self.config["model_gap_solver_tolerance"],
            "require_root_validity": self.config["require_root_validity"],
            "paid_reference": self.config["paid_reference"],
            "hindsight": self.config["hindsight"],
        }

    def model_gap(self, *, purpose="diagnostic"):
        from saddlemill.dimertools.foundation_types import RootSelection
        from saddlemill.dimertools.mode_diagnostics import ModeGapEstimate, compute_model_gap
        if self.physical_hessian_model is None:
            return ModeGapEstimate(
                available=False, value=None, source="physical_hessian_model_spectrum",
                physical=False, root_selection=RootSelection.LOWEST.value,
                selected_root_index=0, selected_root_separation=None, gap_eligible=False,
                degeneracy_unresolved=True, solver_tolerance=self.config["model_gap_solver_tolerance"],
                degeneracy_threshold=self.config["gap_tolerance"],
                unavailable_reason="physical_hessian_model_unavailable",
            )
        result = compute_model_gap(
            self.physical_hessian_model, selected_root_index=0, root_selection=RootSelection.LOWEST,
            solver_tolerance=self.config["model_gap_solver_tolerance"],
            gap_tolerance=self.config["gap_tolerance"], accounting=self.accounting, purpose=purpose,
        )
        if str(purpose).strip().lower() == "algorithm":
            self._last_promotion = {
                "purpose": "algorithm",
                "source_bank": "physical_hessian_model_matrix_recomputed",
                "reused_diagnostic_observation": False,
                "pes_calls_added": 0,
            }
        return result

    def standardize_solver_result(self, result, *, model_gap_purpose="diagnostic"):
        from saddlemill.dimertools.mode_diagnostics import standardize_solver_audit
        record = standardize_solver_audit(
            result, coordinate_space=self.coordinate_space, model_gap=None,
            epsilon=self.config["residual_epsilon"],
        )
        if not (record.gap.available and record.gap.gap_eligible):
            record = standardize_solver_audit(
                result, coordinate_space=self.coordinate_space,
                model_gap=self.model_gap(purpose=model_gap_purpose),
                epsilon=self.config["residual_epsilon"],
            )
        self._last_record = record
        return record

    def standardize_hvp(self, hvp, *, ritz=None, returned_mode=None, model_mode=None,
                        olsen_correction=None, root_valid=True, root_status="selected_root_valid",
                        negative_mode_lost=False, model_gap_purpose="diagnostic",
                        fallback_model_gap=True, **kwargs):
        from saddlemill.dimertools.hvp_interfaces import HVPIdentityError
        from saddlemill.dimertools.mode_diagnostics import standardize_hvp_diagnostic
        common = dict(
            coordinate_space=self.coordinate_space, returned_mode=returned_mode, ritz=ritz,
            epsilon=self.config["residual_epsilon"], gap_tolerance=self.config["gap_tolerance"],
            root_valid=root_valid, root_status=root_status, negative_mode_lost=negative_mode_lost,
            model_mode=model_mode, model_mode_source=kwargs.pop("model_mode_source", "physical_hessian_model" if model_mode is not None else ""),
            olsen_correction=olsen_correction, olsen_correction_source=kwargs.pop("olsen_correction_source", "t09_projected_olsen_correction" if olsen_correction is not None else ""),
            **kwargs,
        )
        try:
            record = standardize_hvp_diagnostic(hvp, model_gap=None, **common)
        except HVPIdentityError:
            common["ritz"] = None
            record = standardize_hvp_diagnostic(
                hvp,
                model_gap=(self.model_gap(purpose=model_gap_purpose) if fallback_model_gap else None),
                **common,
            )
        else:
            if fallback_model_gap and not (record.gap.available and record.gap.gap_eligible):
                record = standardize_hvp_diagnostic(
                    hvp, model_gap=self.model_gap(purpose=model_gap_purpose), **common
                )
        self._last_record = record
        return record

    def standardize_dimer_torque(self, *, evaluated_mode, torque, curvature, geometry_id,
                                  state_id, state_uid, fd_distance, returned_mode=None,
                                  model_gap_purpose="diagnostic"):
        from saddlemill.dimertools.mode_diagnostics import diagnostic_from_dimer_torque
        gap = self.model_gap(purpose=model_gap_purpose)
        record = diagnostic_from_dimer_torque(
            evaluated_mode=evaluated_mode, torque=torque, curvature=curvature,
            coordinate_space=self.coordinate_space, geometry_id=geometry_id,
            state_id=state_id, state_uid=state_uid, fd_distance=fd_distance,
            stencil="central_dimer_endpoints", fd_status="cached_existing_dimer_torque",
            returned_mode=returned_mode, model_gap=gap,
            epsilon=self.config["residual_epsilon"],
        )
        self._last_record = record
        return record

    def evaluate_decision(self, record, *, legacy_refresh_required):
        from saddlemill.dimertools.mode_diagnostics import evaluate_mode_refresh_criterion
        decision = evaluate_mode_refresh_criterion(
            record, selector=self.config["mode_refresh_criterion"],
            mode_residual_threshold=self.config.get("mode_residual_threshold"),
            mode_angular_error_threshold_degrees=self.config.get("mode_angular_error_threshold_degrees"),
            legacy_refresh_required=legacy_refresh_required,
            require_root_validity=self.config["require_root_validity"],
            comparison_tolerance=self.config["comparison_tolerance"],
        )
        self._last_decision = decision
        return decision

    def last_promotion_metadata(self):
        return dict(self._last_promotion)

    def run_paid_reference(self, measure, *, evaluated_mode, snapshots):
        from saddlemill.dimertools.mode_diagnostics import (
            DiagnosticNoninterferenceProbe, run_paid_reference_measurement,
        )
        if not self.config.get("paid_reference", False):
            raise RuntimeError("paid reference diagnostics are not enabled")
        probe = DiagnosticNoninterferenceProbe(snapshots)
        reference, report = run_paid_reference_measurement(
            measure, evaluated_mode=evaluated_mode, coordinate_space=self.coordinate_space,
            accounting=self.accounting, noninterference=probe, strict_noninterference=True,
        )
        self._last_reference = reference
        self._last_reference_noninterference = report
        return reference, report

    def build_hindsight(self, states, *, geometry_convention, final_positions, final_mode,
                        final_curvature, terminal_mode_source, run_converged,
                        terminal_mode_availability_reason=""):
        from saddlemill.dimertools.hindsight import build_hindsight_records
        if not self.config.get("hindsight", False):
            return tuple()
        return build_hindsight_records(
            states, coordinate_space=self.coordinate_space, geometry_convention=geometry_convention,
            final_positions=final_positions, final_mode=final_mode, final_curvature=final_curvature,
            terminal_mode_source=terminal_mode_source, run_converged=run_converged,
            terminal_mode_availability_reason=terminal_mode_availability_reason,
        )

    def status_fields(self):
        fields = {
            "mode_diagnostic_schema": self.mode_diagnostic_schema,
            "mode_diagnostics_enabled": 1,
            "mode_diagnostic_criterion": self.config["mode_refresh_criterion"],
            "mode_refresh_criterion": self.config["mode_refresh_criterion"],
            "mode_residual_threshold": self.config.get("mode_residual_threshold"),
            "mode_angular_error_threshold_degrees": self.config.get("mode_angular_error_threshold_degrees"),
            "mode_residual_epsilon": self.config["residual_epsilon"],
            "mode_gap_tolerance": self.config["gap_tolerance"],
            "mode_model_gap_solver_tolerance": self.config["model_gap_solver_tolerance"],
            "mode_reference_diagnostics_enabled": int(self.config.get("paid_reference", False)),
            "mode_hindsight_enabled": int(self.config.get("hindsight", False)),
        }
        if self._last_record is not None:
            fields["mode_diagnostic_last_record"] = self._last_record.to_dict()
        if self._last_decision is not None:
            fields["mode_diagnostic_last_decision"] = dict(self._last_decision.__dict__)
        if self._last_promotion:
            fields["mode_diagnostic_last_promotion"] = dict(self._last_promotion)
        if self._last_reference is not None:
            ref = self._last_reference
            from saddlemill.dimertools.foundation_types import json_safe
            fields["mode_reference_last"] = {
                "schema": ref.schema,
                "available": bool(ref.available),
                "mode": None if ref.mode is None else np.asarray(ref.mode, dtype=float).tolist(),
                "curvature": ref.curvature,
                "converged": bool(ref.converged),
                "overlap_with_evaluated_mode": ref.overlap_with_evaluated_mode,
                "angle_degrees": ref.angle_degrees,
                "source": ref.source,
                "root_selection": ref.root_selection,
                "pes_calls": int(ref.pes_calls),
                "elapsed_ns": int(ref.elapsed_ns),
                "unavailable_reason": ref.unavailable_reason,
                "metadata": json_safe(ref.metadata),
            }
        if self._last_reference_noninterference is not None:
            fields["mode_reference_last_noninterference"] = dict(
                self._last_reference_noninterference.__dict__
            )
        return fields

    def to_state_dict(self):
        return {
            "schema": self.STATE_SCHEMA,
            "resolved": self.resolved_metadata(),
            "status": self.status_fields(),
            "coordinate_space_id": self.coordinate_space.identity,
        }

    def restore_state_dict(self, state):
        """Restore bounded mode-diagnostics status without replaying any diagnostic work."""
        from saddlemill.dimertools.mode_diagnostics import (
            ModeGapEstimate, ModeRefreshDecision, StandardModeDiagnosticRecord,
        )

        payload = dict(state or {})
        if payload.get("schema") != self.STATE_SCHEMA:
            raise ValueError("unsupported mode-diagnostics runtime state schema")
        if payload.get("coordinate_space_id") != self.coordinate_space.identity:
            raise ValueError("mode-diagnostics resume coordinate-space mismatch")
        status = dict(payload.get("status") or {})
        record_payload = status.get("mode_diagnostic_last_record")
        if record_payload is not None:
            record_data = dict(record_payload)
            record_data.pop("schema", None)
            gap_data = dict(record_data.pop("gap"))
            gap_data.pop("schema", None)
            record_data["gap"] = ModeGapEstimate(**gap_data)
            self._last_record = StandardModeDiagnosticRecord(**record_data)
        decision_payload = status.get("mode_diagnostic_last_decision")
        if decision_payload is not None:
            decision_data = dict(decision_payload)
            decision_data.pop("schema", None)
            self._last_decision = ModeRefreshDecision(**decision_data)
        promotion_payload = status.get("mode_diagnostic_last_promotion")
        self._last_promotion = dict(promotion_payload or {})
        reference_payload = status.get("mode_reference_last")
        if reference_payload is not None:
            from saddlemill.dimertools.mode_diagnostics import ReferenceModeRecord
            reference_data = dict(reference_payload)
            reference_data.pop("schema", None)
            self._last_reference = ReferenceModeRecord(**reference_data)
        noninterference_payload = status.get("mode_reference_last_noninterference")
        if noninterference_payload is not None:
            from saddlemill.dimertools.mode_diagnostics import NoninterferenceReport
            ni = dict(noninterference_payload)
            ni.pop("schema", None)
            ni["changed_labels"] = tuple(ni.get("changed_labels", ()))
            ni["inspected_labels"] = tuple(ni.get("inspected_labels", ()))
            self._last_reference_noninterference = NoninterferenceReport(**ni)
        return self


def _mode_diagnostics_options_from_config(config_dict):
    from saddlemill.dimertools.hvp_interfaces import DEFAULT_GAP_TOLERANCE, DEFAULT_RESIDUAL_EPSILON
    raw = dict(config_dict.get("ourModeDiagnostics", {}) or {})
    enabled = _bool(raw.get("enabled", False))
    criterion = str(raw.get("mode_refresh_criterion", "legacy")).strip().lower()
    valid = {"legacy", "residual", "angular_error", "hybrid"}
    if criterion not in valid:
        raise ValueError(f"[ourModeDiagnostics] mode_refresh_criterion must be one of {sorted(valid)}")
    def optional_float(name):
        value = raw.get(name, None)
        return None if value in (None, "", "none", "None") else float(value)
    opts = {
        "enabled": enabled,
        "mode_refresh_criterion": criterion,
        "mode_residual_threshold": optional_float("mode_residual_threshold"),
        "mode_angular_error_threshold_degrees": optional_float("mode_angular_error_threshold_degrees"),
        "comparison_tolerance": float(raw.get("comparison_tolerance", 0.0)),
        "residual_epsilon": float(raw.get("residual_epsilon", DEFAULT_RESIDUAL_EPSILON)),
        "gap_tolerance": float(raw.get("gap_tolerance", DEFAULT_GAP_TOLERANCE)),
        "model_gap_solver_tolerance": float(raw.get("model_gap_solver_tolerance", 1.0e-4)),
        "require_root_validity": _bool(raw.get("require_root_validity", True)),
        "paid_reference": _bool(raw.get("paid_reference", False)),
        "hindsight": _bool(raw.get("hindsight", False)),
    }
    if enabled and criterion in {"residual", "hybrid"} and opts["mode_residual_threshold"] is None:
        raise ValueError("[ourModeDiagnostics] residual/hybrid requires explicit mode_residual_threshold")
    if enabled and criterion in {"angular_error", "hybrid"} and opts["mode_angular_error_threshold_degrees"] is None:
        raise ValueError("[ourModeDiagnostics] angular_error/hybrid requires explicit mode_angular_error_threshold_degrees")
    finite_tolerances = (
        opts["comparison_tolerance"], opts["residual_epsilon"],
        opts["gap_tolerance"], opts["model_gap_solver_tolerance"],
    )
    if (
        not all(np.isfinite(value) for value in finite_tolerances)
        or opts["comparison_tolerance"] < 0
        or opts["residual_epsilon"] <= 0
        or opts["gap_tolerance"] < 0
        or opts["model_gap_solver_tolerance"] <= 0
    ):
        raise ValueError("[ourModeDiagnostics] tolerances must be finite/nonnegative with residual/model solver tolerances > 0")
    for key in ("mode_residual_threshold", "mode_angular_error_threshold_degrees"):
        if opts[key] is not None and (not np.isfinite(opts[key]) or opts[key] < 0):
            raise ValueError(f"[ourModeDiagnostics] {key} must be finite and >= 0 when set")
    return opts


def create_mode_diagnostics_runtime(config_dict, *, coordinate_space, accounting, physical_hessian_model=None):
    """Build the mode-diagnostics shared runtime, returning ``None`` for strict defaults-off."""
    opts = _mode_diagnostics_options_from_config(config_dict)
    if not opts["enabled"] and not opts["paid_reference"] and not opts["hindsight"]:
        return None
    return ModeDiagnosticsRuntime(
        opts, coordinate_space=coordinate_space, accounting=accounting,
        physical_hessian_model=physical_hessian_model,
    )


__all__ = [
    "DEFAULT_HISTORY_OPTIONS",
    "create_dimer_search",
    "create_mode_diagnostics_runtime",
    "ModeDiagnosticsRuntime",
    "create_rfo_translation_runtime",
    "history_options_from_config",
    "normalize_history_options",
    "partitioned_options_from_config",
    "select_minmode_atoms_class",
    "select_translation_optimizer_class",
    "validate_history_options",
]
