[Main]
executorlib = False
method = NEB
dir_path = /work/08405/ilgar/ls6/saddlemill/examples/catsunami/datasets/all_dft_neb_trajs/transfers  # reads all *.traj files in this directory
Optimizer = MDMin
jobs_per_gpu = 1
Calculator = FAIRChemCalculator  # In the future this could also be Vasp and VaspInteractive
fmax = 0.05
steps = 3000

[FAIRChemCalculator]
device = cuda
model_name_or_path = uma-s-1p1
task_name = oc20

[MDMin]
dt = 0.02
maxstep = 0.1

#[LBFGS]
#alpha = 100
#memory = 50
#maxstep = 0.1

######################## NEB related ########################
[ourNEB]
relax_endpoints = True
endpoint_relax_fmax = 0.01
endpoint_relax_steps = 1000
interpolate_method = ase_linear
num_frames = 10
batch_size = 8
DNEB = True

[DyNEB]
k = 5
method = improvedtangent
climb = True
allow_shared_calculator = True
dynamic_relaxation = False

